name: Run ansible-lint
on:
  pull_request:
    branches: ["main", "stable", "release/v*"]
jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' || 'testing' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build:
    environment: testing
    name: Run ansible-lint
    runs-on: ubuntu-latest
    needs: authorize
    steps:
      - uses: actions/checkout@v6
      - uses: ansible/ansible-lint@main
        env:
          ANSIBLE_GALAXY_SERVER_LIST: certified,validated,galaxy
          ANSIBLE_GALAXY_SERVER_CERTIFIED_URL: https://console.redhat.com/api/automation-hub/content/published/
          ANSIBLE_GALAXY_SERVER_CERTIFIED_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_CERTIFIED_TOKEN: ${{ secrets.AUTOMATION_HUB_TOKEN }}
          ANSIBLE_GALAXY_SERVER_VALIDATED_URL: https://console.redhat.com/api/automation-hub/content/validated/
          ANSIBLE_GALAXY_SERVER_VALIDATED_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_VALIDATED_TOKEN: ${{ secrets.AUTOMATION_HUB_TOKEN }}
          ANSIBLE_GALAXY_SERVER_GALAXY_URL: https://galaxy.ansible.com/api/
